# Generated by Django 5.2.13 on 2026-09-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janSetu', '0010_alter_announcement_options_alter_civicissue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civicissue',
            name='category',
            field=models.CharField(choices=[('Roads', 'Roads'), ('Water', 'Water'), ('Sanitation', 'Sanitation'), ('Electricity', 'Electricity'), ('Waste', 'Waste'), ('Traffic', 'Traffic'), ('Parks', 'Parks')], max_length=50),
        ),
        migrations.AlterField(
            model_name='civicissue',
            name='status',
            field=models.CharField(choices=[('Reported', 'Reported'), ('AI Verified', 'AI Verified'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Pending Citizen Verification', 'Pending Citizen Verification'), ('Verified Resolved', 'Verified Resolved')], default='Reported', max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationitem',
            name='notification_type',
            field=models.CharField(max_length=50),
        ),
    ]
