# Generated by Django 5.2.13 on 2026-10-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janSetu', '0011_alter_civicissue_category_alter_civicissue_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civicissue',
            name='category',
            field=models.CharField(choices=[('Roads', 'Roads'), ('Water', 'Water'), ('Sanitation', 'Sanitation'), ('Electricity', 'Electricity'), ('Waste', 'Waste'), ('Traffic', 'Traffic'), ('Parks', 'Parks'), ('Innovation', 'Innovation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='civicissue',
            name='status',
            field=models.CharField(choices=[('Reported', 'Reported'), ('AI Verified', 'AI Verified'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Pending Citizen Verification', 'Pending Citizen Verification'), ('Verified Resolved', 'Verified Resolved'), ('Under Review', 'Under Review'), ('Feasibility Approved', 'Feasibility Approved'), ('Pilot Scheduled', 'Pilot Scheduled'), ('Budget Allocated', 'Budget Allocated')], default='Reported', max_length=100),
        ),
    ]
